"""Supabase client setup for the QuoteStack backend.

Required tables (PostgreSQL / Supabase SQL):

-- Deals table
-- create table if not exists deals (
--   id bigint generated by default as identity primary key,
--   name text not null,
--   value numeric null,
--   created_at timestamptz not null default now()
-- );

-- Quotes table
-- create table if not exists quotes (
--   id bigint generated by default as identity primary key,
--   deal_id bigint not null references deals(id) on delete cascade,
--   supplier text null,
--   price numeric not null,
--   currency text null,
--   lead_time_days integer null,
--   moq integer null,
--   created_at timestamptz not null default now()
-- );
"""

from functools import lru_cache
import os

from supabase import Client, create_client


def _get_env(key: str) -> str:
    """Read a required environment variable, raising if missing."""
    value = os.environ.get(key)
    if not value:
        raise RuntimeError(f"Missing required environment variable: {key}")
    return value


@lru_cache(maxsize=1)
def get_supabase_client() -> Client:
    """Return a cached Supabase client."""
    url = _get_env("SUPABASE_URL")
    key = _get_env("SUPABASE_SERVICE_ROLE_KEY")
    return create_client(url, key)


__all__ = ["get_supabase_client"]
